Repository hmcts/pip-data-management, pull requests merged in 2021-11, with the labels that each got.

#20 PUB-721: Glossary API
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/CaseEventGlossaryController.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/database/CourtsAndHearings.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/models/lcsu/CaseEventGlossary.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/service/CaseEventGlossaryService.java
  src/main/resources/mocks/CaseEventGlossary.json
  src/test/java/uk/gov/hmcts/reform/pip/data/management/api/CaseEventGlossaryTest.java
  src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/CaseEventGlossaryControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/data/management/database/CourtsAndHearingsTest.java
  src/test/java/uk/gov/hmcts/reform/pip/data/management/helpers/EventGlossaryHelper.java
  src/test/java/uk/gov/hmcts/reform/pip/data/management/service/CourtEventGlossaryServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-20

#24 updated court and hearing data to new data set
  src/main/resources/mocks/courtsAndHearingsCount.json
  src/main/resources/mocks/hearingsList.json
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-24

#28 Pub 721
  src/main/resources/mocks/liveCaseStatusUpdates.json
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-28

#29 PUB-888 - Added ' to magistrates
  src/main/resources/mocks/courtsAndHearingsCount.json
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-29

#30 updated incorrect jurisdiction
  src/main/resources/mocks/courtsAndHearingsCount.json
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-30
