Repository hmcts/pip-data-management, pull requests merged in 2022-06, with the labels that each got.

#120 PUB-1354 - Resize DB
  config/owasp/suppressions.xml
  infrastructure/tf-apim-api.tf
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-120

#117 Pub 1312 Sensitivity Updates
  charts/pip-data-management/Chart.yaml
  charts/pip-data-management/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
  src/integrationTest/resources/application-test.yaml
  src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationController.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/database/ArtefactRepository.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/errorhandling/GlobalExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/models/request/PiUser.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/models/request/Roles.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/models/request/UserProvenances.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/service/AccountManagementService.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/data/management/service/AccountManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationServiceTest.java
  src/test/resources/application-test.yaml
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-117

#125 PUB-1409 - correct url for prod
  config/owasp/suppressions.xml
  infrastructure/main.tf
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-125
