Repository hmcts/pip-data-management, pull requests merged in 2023-10, with the labels that each got.

#463 PUB-2130 Create Postgres 15 Azure Flexible Server
  infrastructure/providers.tf
  infrastructure/tf-db-flexible-secrets.tf
  infrastructure/tf-db-flexible.tf
  infrastructure/variables.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-463

#466 PUB-2157 - Add in Flexible Server extensions
  infrastructure/tf-db-flexible.tf
Labels: ns:pip, prd:pip, destroy, rel:pip-data-management-pr-466

#470 PUB-2188 - Migrate lower envs demo
  infrastructure/tf-db-flexible.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-470

#473 PUB-2188 - Suppression
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-473

#474 PUB-2188 - Migrate lower envs
  infrastructure/tf-db-flexible.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-474

#471 Pub 2164
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/pip/data/management/database/ArtefactRepository.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
  src/test/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-471

#475 PUB-2188 - Migrate Lower Envs - Staging
  build.gradle
  config/owasp/suppressions.xml
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, destroy, rel:pip-data-management-pr-475

#477 Pub 2188 migrate lower envs
  charts/pip-data-management/values.stg.template.yaml
  infrastructure/tf-db-flexible.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-477

#478 Pub 2188 migrate lower envs
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-478

#467 PUB-2192 - Monthly Updates
  .github/workflows/ci.yml
  build.gradle
  charts/pip-data-management/Chart.yaml
  charts/pip-data-management/values.yaml
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-467, enable_keep_helm

#479 PUB-2192 - Changed chart back
  charts/pip-data-management/Chart.yaml
  charts/pip-data-management/values.yaml
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-479

#480 PUB-2192 - Chart Update Workload Identity
  charts/pip-data-management/Chart.yaml
  charts/pip-data-management/values.dev.template.yaml
  charts/pip-data-management/values.stg.template.yaml
  charts/pip-data-management/values.yaml
Labels: ns:pip, prd:pip, enable_keep_helm, rel:pip-data-management-pr-480

#482 PUB-2188 - Migrate lower envs
  build.gradle
  config/owasp/suppressions.xml
  infrastructure/tf-db-secrets.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-482

#484 PUB-2188 - Added Staging
  charts/pip-data-management/values.stg.template.yaml
  infrastructure/tf-db-secrets.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-484

#476 PUB-1969 OPA_PRESS_LIST validation schema
  build.gradle
  infrastructure/resources/swagger/api-swagger.json
  src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/lists/PublicationOpaPressLIstTest.java
  src/functionalTest/resources/data/opa-press-list/opaPressList.json
  src/functionalTest/resources/data/opa-press-list/opaPressListInvalid.json
  src/main/resources/application.yaml
  src/main/resources/schemas/master_schema.json
  src/main/resources/schemas/opa_press_list.json
  src/test/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/OpaPressListTest.java
  src/test/resources/mocks/opa-press-list/opaPressList.json
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-476

#485 PUB-2189 - Removed old role
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-485

#487 PUB-2189 - Part 2
  infrastructure/tf-db-flexible.tf
  infrastructure/tf-db-secrets.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-487

#481 Pub 1968 - OPA Public List
  build.gradle
  infrastructure/resources/swagger/api-swagger.json
  src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/lists/PublicationOpaPublicListTest.java
  src/functionalTest/resources/data/opa-public-list/opaPublicList.json
  src/functionalTest/resources/data/opa-public-list/opaPublicListInvalid.json
  src/main/resources/application.yaml
  src/main/resources/schemas/opa_public_list.json
  src/test/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/OpaPublicListTest.java
  src/test/resources/mocks/opa-public-list/opaPublicList.json
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-481
