Repository hmcts/pip-data-management, pull requests merged in 2023-11, with the labels that each got.

#491 PUB-2222 - Removed old config
  infrastructure/providers.tf
  infrastructure/tf-db-flexible.tf
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-491

#492 PUB-2222 - Switched over old values
  infrastructure/tf-db-flexible-secrets.tf
  infrastructure/tf-db-secrets.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-492

#494 PUB-2222 - Remove old postgres
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-494

#496 PUB-2222 - Remove old postgres from ITHC + Staging
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, destroy, rel:pip-data-management-pr-496

#499 PUB-2222 - Updated permissions
  infrastructure/tf-db-flexible.tf
Labels: ns:pip, prd:pip, destroy, rel:pip-data-management-pr-499

#497 PUB-2222 - Removed old postgres
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-data-management-pr-497

#498 PUB-2222 - Removed old postgres part 2
  infrastructure/tf-db-flexible-secrets.tf
  infrastructure/tf-db-flexible.tf
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, destroy, rel:pip-data-management-pr-498

#500 PUB-1673 SJP Public List validation schema update
  src/functionalTest/resources/data/sjp-public-list/sjpPublicList.json
  src/main/resources/schemas/single_justice_procedure_public.json
  src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPublicListTest.java
  src/test/resources/mocks/sjp-public-list/sjpPublicList.json
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-500

#501 PUB-2230 Handle parties for hearing with multiple cases
  src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
  src/main/java/uk/gov/hmcts/reform/pip/data/management/utils/JsonExtractor.java
  src/test/java/uk/gov/hmcts/reform/pip/data/management/utils/JsonExtractorTest.java
  src/test/resources/mocks/jsonPayloadWithParties.json
Labels: ns:pip, prd:pip, rel:pip-data-management-pr-501

#502 PUB-2206 - Updated versions + suppressions
  build.gradle
  config/owasp/suppressions.xml
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, add-or-update, enable_keep_helm, rel:pip-data-management-pr-502
